---
title: "Labb1"
author: "Daniel Svedlund"
date: "2024-11-18"
output:
  pdf_document: default
  html_document: default
---
\renewcommand{\figurename}{Figur} 
\renewcommand{\tablename}{Tabell}

# Sammanfattning
I detta inledande stycke ska du förklara vad labben går ut på, utan att gå in
på detaljer.

# Uppgift 2

```{r}
observations <- 10000
```

## Uppgift 2.1: Normalfördelade data
```{r, fig.cap = paste("Boxplot för 8 olika slumpförsök med", observations, "observationer från en normalfördelning med väntevärde 20 och standardavvikelse 20.")}

set.seed(19930920)

x1 <- rnorm(observations, 20, 20)
x2 <- rnorm(observations, 20, 20)
x3 <- rnorm(observations, 20, 20)
x4 <- rnorm(observations, 20, 20)
x5 <- rnorm(observations, 20, 20)
x6 <- rnorm(observations, 20, 20)
x7 <- rnorm(observations, 20, 20)
x8 <- rnorm(observations, 20, 20)

boxplot(x1, x2, x3, x4, x5, x6, x7, x8)
```

```{r, fig.cap = paste("Histogram för de 8 slumpförsök med", observations, "observationer från en normalfördelning med väntevärde 20 och standardavvikelse 20. Linjen visar den teoretiska normalfördelningen med väntevärde 20 och standardavvikelse 20.")}

old_par <- par(mfrow = c(2, 4)) # 2 rader, 4 kolonner

hist(x1, prob=TRUE)
x <- seq(from = -20, to = 70, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x2, prob=TRUE)
x <- seq(from = -10, to = 70, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x3, prob=TRUE)
x <- seq(from = -10, to = 60, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x4, prob=TRUE)
x <- seq(from = -10, to = 70, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x5, prob=TRUE)
x <- seq(from = -60, to = 60, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x6, prob=TRUE)
x <- seq(from = -30, to = 60, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x7, prob=TRUE)
x <- seq(from = -40, to = 60, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(x8, prob=TRUE)
x <- seq(from = -30, to = 50, length.out = 100)
lines(x, dnorm(x, 20, 20))

par(old_par)
```

```{r, fig.cap = paste("Normalfördelningsplottar för de 8 slumpförsök med", observations, "observationer från en normalfördelning med väntevärde 20 och standardavvikelse 20.")}

old_par <- par(mfrow = c(2, 4)) # 2 rader, 4 kolonner

qqnorm(x1)
qqline(x1)

qqnorm(x2)
qqline(x2)

qqnorm(x3)
qqline(x3)

qqnorm(x4)
qqline(x4)

qqnorm(x5)
qqline(x5)

qqnorm(x6)
qqline(x6)

qqnorm(x7)
qqline(x7)

qqnorm(x8)
qqline(x8)

par(old_par)
```

\newpage

## Uppgift 2.2: Likformigt fördelade data

```{r, fig.cap = paste("Boxplot för 5 olika slumpförsök med", observations, "observationer från en likformig fördelning med väntevärde 20 och standardavvikelse 20.")}

set.seed(19930920)

u1 <- runif(observations, 20 - sqrt(3), 20 + sqrt(3))
u2 <- runif(observations, 20 - sqrt(3), 20 + sqrt(3))
u3 <- runif(observations, 20 - sqrt(3), 20 + sqrt(3))
u4 <- runif(observations, 20 - sqrt(3), 20 + sqrt(3))
u5 <- runif(observations, 20 - sqrt(3), 20 + sqrt(3))

boxplot(u1, u2, u3, u4, u5)
```

```{r, fig.cap = paste("Histogram för slumpförsök u1, u2 med", observations, "observationer från en likformig fördelning med väntevärde 20 och standardavvikelse 20. Heldragna strecket visar teoretiska normalfördelningen med väntevärde 20 och standardavvikelse 20 på motsvarande intervall.")}

old_par <- par(mfrow = c(1, 2)) # 1 rad, 2 kolonner

hist(u1, prob=TRUE)
x <- seq(from = 18, to = 22, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(u2, prob=TRUE)
x <- seq(from = 18, to = 22, length.out = 100)
lines(x, dnorm(x, 20, 20))

par(old_par)
```

```{r, fig.cap = paste("Histogram för slumpförsök u3, u4, u5 med", observations, "observationer från en likformig fördelning med väntevärde 20 och standardavvikelse 20. Heldragna strecket visar teoretiska normalfördelningen med väntevärde 20 och standardavvikelse 20 på motsvarande intervall.")}

old_par <- par(mfrow = c(1, 3)) # 1 rad, 3 kolonner

hist(u3, prob=TRUE)
x <- seq(from = 18, to = 22, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(u4, prob=TRUE)
x <- seq(from = 18, to = 22, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(u5, prob=TRUE)
x <- seq(from = 18, to = 22, length.out = 100)
lines(x, dnorm(x, 20, 20))

par(old_par)
```

```{r, fig.cap = paste("Normalfördelningsplottar för slumpförsök u1, u2 med", observations, "observationer från en likformig fördelning med väntevärde 20 och standardavvikelse 20.")}

old_par <- par(mfrow = c(1, 2)) # 1 rad, 2 kolonner

qqnorm(u1)
qqline(u1)

qqnorm(u2)
qqline(u2)

par(old_par)
```

```{r, fig.cap = paste("Normalfördelningsplottar för slumpförsök u3, u4, u5 med", observations, "observationer från en likformig fördelning med väntevärde 20 och standardavvikelse 20.")}

old_par <- par(mfrow = c(1, 3)) # 1 rad, 3 kolonner

qqnorm(u3)
qqline(u3)

qqnorm(u4)
qqline(u4)

qqnorm(u5)
qqline(u5)
```

## Uppgift 2.3: Exponentialfördelade data

```{r, fig.cap = paste("Boxplot för 5 olika slumpförsök med", observations, "observationer från en expoentialfördelning med väntevärde 20.")}

set.seed(19930920)

e1 <- rexp(observations, 1/20)
e2 <- rexp(observations, 1/20)
e3 <- rexp(observations, 1/20)
e4 <- rexp(observations, 1/20)
e5 <- rexp(observations, 1/20)

boxplot(e1, e2, e3, e4, e5)
```

```{r, fig.cap = paste("Histogram för slumpförsök e1, e2 med", observations, "observationer från en exponentialfördelning med väntevärde 20. Linjen visar teoretiska normalfördelningen med väntevärde 20 och standardavvikelse 20.")}

old_par <- par(mfrow = c(1, 2)) # 1 rad, 2 kolonner

hist(e1, prob=TRUE)
x <- seq(from = 0, to = 200, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(e2, prob=TRUE)
x <- seq(from = 0, to = 200, length.out = 100)
lines(x, dnorm(x, 20, 20))

par(old_par)
```

```{r, fig.cap = paste("Histogram för slumpförsök e3, e4, e5 med", observations, "observationer från en exponentialfördelning med väntevärde 20. Linjen visar teoretiska normalfördelningen med väntevärde 20 och standardavvikelse 20.")}

old_par <- par(mfrow = c(1, 3)) # 1 rad, 3 kolonner

hist(e3, prob=TRUE)
x <- seq(from = 0, to = 200, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(e4, prob=TRUE)
x <- seq(from = 0, to = 200, length.out = 100)
lines(x, dnorm(x, 20, 20))

hist(e5, prob=TRUE)
x <- seq(from = 0, to = 200, length.out = 100)
lines(x, dnorm(x, 20, 20))

par(old_par)
```

```{r, fig.cap = paste("Normalfördelningsplottar för slumpförsök e1, e2 med", observations, "observationer från en exponentialfördelning med väntevärde 20.")}

old_par <- par(mfrow = c(1, 2)) # 1 rad, 2 kolonner

qqnorm(e1)
qqline(e1)

qqnorm(e2)
qqline(e2)

par(old_par)
```

```{r, fig.cap = paste("Normalfördelningsplottar för slumpförsök e3, e4, e5 med", observations, "observationer från en exponentialfördelning med väntevärde 20.")}

old_par <- par(mfrow = c(1, 3)) # 1 rad, 3 kolonner

qqnorm(e3)
qqline(e3)

qqnorm(e4)
qqline(e4)

qqnorm(e5)
qqline(e5)

par(old_par)
```
